### ISSUE TITLE
No way to do nothing from carthage-console

### ISSUE THREAD

**Issue by kdienes** [Hadron/carthage#20]
I'd like to have a way to start carthage-console to access the layout while doing as little as possible, and possibly even a way to skip resolve_networking().

This was motivated by trying to figure out why a carthage run was hanging before creating the console, which doesn't turn out to be a good example, but it's something I've wished for in general.

I'd like to consider changing the behavior of "no arguments" to do nothing and to require --start or --generate for simplicity, but I'm not sure what my opinion is beyond wanting to consider it.  Am I correct that doing --start on any single host will trigger all of the behavior of --generate?

**Comment by hartmans** [comment]
To clarify, --start on one host will not imply all of --generate in most layouts.  It will imply resolve_networking, and will instantiate (in not ready state) all the MachineModels, but will not generate.
